name: Run secret key
on:
  push:
     branches: [ main ]
jobs:

steps:
      env:
       ACCESSTOKEN: ${{secrets.ACCESSTOKEN}}
       ACCESSTOKENSECRET: ${{secrets.ACCESSTOKENSECRET}}
       CONSUMERKEY: ${{secrets.CONSUMERKEY}}
       CONSUMERSECRET: ${{secrets.CONSUMERSECRET}}
  
      
