name: Run secret key
on:
  push:
     branches: [ main ]
jobs:
example_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [10, 12, 14]

steps:
      env:
       ACCESSTOKEN: ${{secrets.ACCESSTOKEN}}
       ACCESSTOKENSECRET: ${{secrets.ACCESSTOKENSECRET}}
       CONSUMERKEY: ${{secrets.CONSUMERKEY}}
       CONSUMERSECRET: ${{secrets.CONSUMERSECRET}}
  
      
